INSERT OR REPLACE INTO site_settings (key, value) VALUES
('site_name', 'Asri Digital'),
('site_url', 'https://asridigital.com'),
('site_description', 'Solusi Bisnis Digital & AI untuk Profesional Indonesia'),
('hero_title', 'Solusi Digital Instan untuk Kerja Lebih Cepat.'),
('hero_subtitle', 'Temukan aplikasi praktis, data riset tren terupdate, dan asisten AI kustom yang siap pakai hari ini. Sekali bayar, tanpa biaya langganan bulanan.'),
('hero_cta_text', 'Lihat Semua Produk'),
('hero_cta_link', '#produk'),
('stat_active_users', '500+'),
('stat_active_users_label', 'Pengguna Aktif'),
('stat_products_sold', '1,000+'),
('stat_products_sold_label', 'Produk Terjual'),
('stat_rating', '4.9/5'),
('stat_rating_label', 'Rating Kepuasan'),
('catalog_section_title', 'Eksplorasi Katalog Digital'),
('catalog_section_description', 'Temukan tools dan aset digital yang dirancang khusus untuk mempercepat alur kerja dan riset pasar Anda.'),
('feature_1_title', 'Akses Instan'),
('feature_1_description', 'File langsung dapat diunduh setelah pembayaran.'),
('feature_1_icon', 'zap'),
('feature_2_title', 'Pembayaran Aman'),
('feature_2_description', 'Dienkripsi dan diproses oleh payment gateway terpercaya.'),
('feature_2_icon', 'lock'),
('feature_3_title', 'Dukungan Lokal'),
('feature_3_description', 'Produk dirancang khusus untuk pasar & bahasa Indonesia.'),
('feature_3_icon', 'message-square'),
('feature_4_title', 'Update Gratis'),
('feature_4_description', 'Dapatkan versi terbaru dari produk yang Anda beli selamanya.'),
('feature_4_icon', 'refresh-cw'),
('promo_badge_text', 'BEST VALUE'),
('promo_title', 'Miliki Semua Aset & Tools Selamanya.'),
('promo_description', 'Akses ke seluruh aplikasi, data riset, dan Custom GPT yang ada sekarang, plus semua produk baru yang akan kami rilis di masa depan. Bayar sekali, pakai seumur hidup.'),
('promo_cta_text', 'Amankan All-Access Pass Sekarang'),
('promo_compare_price', '750000'),
('footer_tagline', 'Dapatkan inspirasi alur kerja, update software, dan tips produktivitas harian.'),
('copyright_text', 'Asri Digital by Creator. All rights reserved.'),
('social_linkedin', '#'),
('social_twitter', '#'),
('default_product_image', '/images/placeholder.jpg');